{
 "title": "concurents",
 "time": { "from": "2021-11-09T11:00:03.500Z", "to": "2022-07-07T10:59:47.500Z" },
 "templating": {
  "list": [
   { "name": "categorie", "label": "Catégorie", "query": "5" },
   { "name": "fabricant", "label": "Fabricant", "query": "527" }
  ]
 },
 "panels": [
  {
   "title": "Score de santé",
   "type": "gauge",
   "description": "Pourcentage de la production d'un fabricant sur l'offre du top 10 des magasins des produits d'une certaine catégorie.",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "apiformation",
     "rawSql": "SELECT\n  AVG(sq.pourcentage)\nFROM\n  (\n    WITH top10 as (\n      SELECT\n        COUNT(id) as nbVente,\n        magID\n      FROM\n        `myLogLoader_accordsventelog`\n      WHERE\n        catID = '$categorie'\n      GROUP BY\n        magID\n      ORDER BY\n        `nbVente` DESC\n      LIMIT\n        10\n    )\n    SELECT\n      (COUNT(id) * 100) / nbVente AS pourcentage,\n      nbVente,\n      top10.magID\n    FROM\n      myLogLoader_accordsventelog ac\n      JOIN top10 ON ac.catID = '$categorie'\n      AND ac.magID = top10.magID\n      AND ac.fabID = '$fabricant'\n      AND $__timeFilter(dateID)\n    GROUP BY\n      top10.magID\n  ) as sq;"
    }
   ]
  },
  {
   "title": "Fabricants par catégorie",
   "type": "stat",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "apiformation",
     "rawSql": "SELECT COUNT(DISTINCT(fabID)) as `Nombre de fabricants` FROM `myLogLoader_produitlog` WHERE catID = '$categorie' AND $__timeFilter(dateID);"
    }
   ]
  },
  {
   "title": "Moyenne de production par catégorie",
   "type": "gauge",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "first" ] } },
   "targets": [
    {
     "dataset": "apiformation",
     "rawSql": "SELECT\n  AVG(nb_prod),\n  MAX(nb_prod) as Max\nFROM\n  (\n    SELECT\n      COUNT(prodID) as nb_prod\n    FROM\n      `myLogLoader_produitlog`\n    WHERE\n      catID = '$categorie'\n      AND  $__timeFilter(dateID)\n    GROUP BY\n      fabID\n  ) AS subquery;"
    }
   ]
  },
  {
   "title": "Top 10",
   "type": "table",
   "description": "Top 10 des magasins par catégorie de produit",
   "gridPos": { "h": 16, "w": 12, "x": 0, "y": 9 },
   "targets": [
    {
     "dataset": "apiformation",
     "rawSql": "SELECT\n  nb_prod as 'Nombre de produits',\n  Magasins\nFROM\n  (\n    SELECT\n      COUNT(DISTINCT(prodID_id)) as nb_prod,\n      magID as Magasins\n    FROM\n      etlt.myLogLoader_accordsventelog\n    WHERE\n      catID = '$categorie'\n      AND $__timeFilter(dateID) \n    GROUP BY\n      Magasins\n    order by\n      nb_prod DESC\n    LIMIT\n      10\n  ) AS sq"
    }
   ]
  },
  {
   "title": "Nombre de fabricants par mois",
   "type": "timeseries",
   "gridPos": { "h": 16, "w": 12, "x": 12, "y": 9 },
   "targets": [
    {
     "dataset": "apiformation",
     "rawSql": "SELECT\n\tdateID as time,\n    COUNT(DISTINCT fabID) as Fabricants\n  FROM\n    `myLogLoader_accordsventelog`\n  WHERE\n    catID = '$categorie'\n  GROUP BY\n    DATE_FORMAT(dateID, '%Y-%m')"
    }
   ]
  }
 ]
}