{
 "title": "KPI etlt",
 "time": { "from": "2021-12-31T23:00:00.000Z", "to": "2022-12-31T22:59:59.000Z" },
 "refresh": "5s",
 "templating": {
  "list": [
   {
    "name": "categorie",
    "label": "Catégorie",
    "query": "select distinct catID from etlt.myLogLoader_produitlog ORDER BY catID"
   },
   {
    "name": "fabricant",
    "label": "Fabricant",
    "query": "SELECT DISTINCT fabID FROM etlt.myLogLoader_accordsventelog WHERE catID = $categorie"
   }
  ]
 },
 "panels": [
  { "title": "KPIs", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 }, "repeat": "categorie" },
  {
   "title": "Score de santé",
   "type": "barchart",
   "description": "Pourcentage de la production d'un fabricant sur l'offre du top 10 des magasins des produits d'une certaine catégorie.",
   "gridPos": { "h": 12, "w": 14, "x": 0, "y": 1 },
   "targets": [
    {
     "dataset": "apiformation",
     "rawSql": "\n    WITH top10 as (\n      SELECT\n        COUNT(id) as nbVente,\n        magID\n      FROM\n        `myLogLoader_accordsventelog`\n      WHERE\n        catID = '$categorie'\n      GROUP BY\n        magID\n      ORDER BY\n        `nbVente` DESC\n      LIMIT\n        10\n    )\n    SELECT\n      (COUNT(id) * 100) / nbVente AS 'Part produite par le fabricant $fabricant',\n      nbVente as 'Nombre de ventes',\n      top10.magID\n    FROM\n      myLogLoader_accordsventelog ac\n      JOIN top10 ON ac.catID = '$categorie'\n      AND ac.magID = top10.magID\n      AND ac.fabID = '$fabricant'\n      AND $__timeFilter(dateID)\n    GROUP BY\n      top10.magID"
    }
   ]
  },
  {
   "title": "Top 10",
   "type": "table",
   "description": "Top 10 des magasins par catégorie de produit",
   "gridPos": { "h": 15, "w": 9, "x": 14, "y": 1 },
   "targets": [
    {
     "dataset": "apiformation",
     "rawSql": "SELECT\n  nb_prod as 'Nombre de produits',\n  Magasins\nFROM\n  (\n    SELECT\n      COUNT(DISTINCT(prodID_id)) as nb_prod,\n      magID as Magasins\n    FROM\n      etlt.myLogLoader_accordsventelog\n    WHERE\n      catID = '$categorie'\n      AND $__timeFilter(dateID) \n    GROUP BY\n      Magasins\n    order by\n      nb_prod DESC\n    LIMIT\n      10\n  ) AS sq"
    }
   ]
  },
  {
   "title": "Nombre de fabricants par période",
   "type": "timeseries",
   "gridPos": { "h": 14, "w": 12, "x": 0, "y": 13 },
   "targets": [
    {
     "dataset": "apiformation",
     "rawSql": "SELECT\n  dateID as time,\n  COUNT(DISTINCT fabID) as Fabricants\nFROM\n  `myLogLoader_accordsventelog`\nWHERE\n  catID = '$categorie'\nGROUP BY\n  DATE_FORMAT(dateID, '%Y-%m')"
    }
   ]
  },
  {
   "title": "Moyenne de production par catégorie",
   "type": "gauge",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 16 },
   "options": { "reduceOptions": { "calcs": [ "first" ] } },
   "targets": [
    {
     "dataset": "apiformation",
     "rawSql": "SELECT\n  AVG(nb_prod),\n  MAX(nb_prod) as Max\nFROM\n  (\n    SELECT\n      COUNT(prodID) as nb_prod\n    FROM\n      `myLogLoader_produitlog`\n    WHERE\n      catID = '$categorie'\n      AND  $__timeFilter(dateID)\n    GROUP BY\n      fabID\n  ) AS subquery;"
    }
   ]
  },
  {
   "title": "Fabricants par catégorie",
   "type": "stat",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 26 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "apiformation",
     "rawSql": "SELECT COUNT(DISTINCT(fabID)) as `Nombre de fabricants` FROM `myLogLoader_produitlog` WHERE catID = '$categorie' AND $__timeFilter(dateID);"
    }
   ]
  },
  {
   "title": "Fabricants par produits",
   "type": "table",
   "gridPos": { "h": 13, "w": 12, "x": 0, "y": 27 },
   "targets": [
    {
     "dataset": "etlt",
     "rawSql": "SELECT\n  COUNT(prodID) AS 'Nombre de produits',\n  fabID as Fabricants\nFROM\n  etlt.myLogLoader_produitlog\n  WHERE catID = $categorie \nGROUP BY\n  fabID"
    }
   ]
  }
 ]
}