apiVersion: v1
kind: Service
metadata:
  name: mysql
spec:
  selector:
    app: etlt-stack
  ports:
    - protocol: TCP
      port: 3307
      targetPort: 3306
  clusterIP: None  # Headless service for internal access
---
apiVersion: v1
kind: Service
metadata:
  name: phpmyadmin
spec:
  selector:
    app: etlt-stack
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 80
  type: LoadBalancer
---
apiVersion: v1
kind: Service
metadata:
  name: grafana
spec:
  selector:
    app: etlt-stack
  ports:
    - protocol: TCP
      port: 3100
      targetPort: 3000
  type: LoadBalancer

